# Generated by Django 5.0.3 on 2024-04-01 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'max_length': 'bokatas_store.products.models name must conatain max 50'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='bokatas_store.products.models name must contain at latest 3')]),
        ),
    ]
