# Generated by Django 5.0.3 on 2024-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPictures',
            new_name='ProductPicture',
        ),
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name_plural': 'product pictures'},
        ),
    ]
