# Generated by Django 5.0.3 on 2024-04-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productquantity_order'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order'),
        ),
    ]
