# Generated by Django 5.0.3 on 2024-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.webp', upload_to='mediafiles/profile_pictures'),
        ),
    ]
